# Generated by Django 2.2.3 on 2019-07-24 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190723_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_edit_author', 'Can edit author data'),)},
        ),
    ]
