# Generated by Django 2.2.3 on 2019-07-24 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190724_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_edit_book', 'Can edit book data'),)},
        ),
    ]
